<!--NAVIGATION-->
< [数组排序](02.08-Sorting.ipynb) | [目录](Index.ipynb) | [使用Pandas进行数据处理](03.00-Introduction-to-Pandas.ipynb) >

<a href="https://colab.research.google.com/github/wangyingsm/Python-Data-Science-Handbook/blob/master/notebooks/02.09-Structured-Data-NumPy.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# Structured Data: NumPy's Structured Arrays

# 格式化數據：NumPy裡的格式化數組

> While often our data can be well represented by a homogeneous array of values, sometimes this is not the case. This section demonstrates the use of NumPy's *structured arrays* and *record arrays*, which provide efficient storage for compound, heterogeneous data.  While the patterns shown here are useful for simple operations, scenarios like this often lend themselves to the use of Pandas ``Dataframe``s, which we'll explore in [Chapter 3](03.00-Introduction-to-Pandas.ipynb).

雖然我們的數據很多情況下都能表示成同種類的數組，但是某些情況下，這是不適用的。本小節展示瞭如何使用NumPy的*結構化數組*和*記錄數組*，它們能夠提供對於復合的，不同種類的數組的有效存儲方式。本小節的內容，包括場景和操作，通常都會在Pandas的`Dataframe`中使用，有關內容我們會在[第三章](03.00-Introduction-to-Pandas.ipynb)中詳細討論。

In [1]:
import numpy as np
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

> But this is a bit clumsy. There's nothing here that tells us that the three arrays are related; it would be more natural if we could use a single structure to store all of this data.
NumPy can handle this through structured arrays, which are arrays with compound data types.

顯然這種做法有些原始。沒有任何額外的信息讓我們知道這三個數組是關聯的；如果我們可以使用一個結構保存所有這些數據的話，會更加的自然。 NumPy使用結構化數組來處理這種情況，結構化數組可以用來存儲複合的數據類型。

In [2]:
x = np.zeros(4, dtype=int)

> We can similarly create a structured array using a compound data type specification:Here ``'U10'`` translates to "Unicode string of maximum length 10," ``'i4'`` translates to "4-byte (i.e., 32 bit) integer," and ``'f8'`` translates to "8-byte (i.e., 64 bit) float."
We'll discuss other options for these type codes in the following section.

我們也可以類似的創建一個複合類型的數組，只需要指定相應的dtype數據類型即可：這裡的`U10`代表著“Unicode編碼的字符串，最大長度10”，`i4`代表著“4字節（32比特）整數”，`f8`代表著“8字節（64比特）浮點數”。本節後面我們會介紹其他的類型選項。

In [3]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


> Now that we've created an empty container array, we can fill the array with our lists of values:

現在我們已經創建了一個空的結構化數組，我們可以使用上面的數據列表將數據填充到數組中：

In [4]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


> As we had hoped, the data is now arranged together in one convenient block of memory.The handy thing with structured arrays is that you can now refer to values either by index or by name:

正如我們希望那樣，數組的數據現在被存儲在一整塊的內存空間中。使用結構化數組的方便的地方是你可以使用字段的名稱而不是序號來訪問元素值了：

In [5]:
# 獲得所有的名字
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [6]:
# 獲得第一行
data[0]

('Alice', 25, 55.)

In [7]:
# 獲得最後一行的名字
data[-1]['name']

'Doug'

In [8]:
# 獲得所有年齡小於30的人的姓名
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

> Note that if you'd like to do any operations that are any more complicated than these, you should probably consider the Pandas package, covered in the next chapter.

請注意，如果你想要完成的工作比上面的需求還要復雜的話，你應該考慮使用Pandas包。

## Creating Structured Arrays

## 創建結構化數組

In [9]:
# Structured array : the dictionary method
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
# specified using Python types or NumPy dtypes instead
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [11]:
#specified as a list of tuples
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
# pecify the types alone in a comma-separated string
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

> The shortened string format codes may seem confusing, but they are built on simple principles.
The first (optional) character is ``<`` or ``>``, which means "little endian" or "big endian," respectively, and specifies the ordering convention for significant bits.
The next character specifies the type of data: characters, bytes, ints, floating points, and so on (see the table below).
The last character or characters represents the size of the object in bytes.

類型的字符串形式的縮寫初看起來很困惑，但實際上它們都是依據簡單原則得到的。第一個（可選的）字符是`<`或`>`，代表這類型是`小尾`還是`大尾`，用來指定存儲的字節序。下一個字符指定數據類型：字符、字節、整數、浮點數或其他（見下表）。最後一個字符代表類型的長度。

| 字符        | 說明           | 舉例                             |
| ---------        | -----------           | -------                             | 
| ``'b'``          | 字節                  | ``np.dtype('b')``                   |
| ``'i'``          | 帶符號整數        | ``np.dtype('i4') == np.int32``      |
| ``'u'``          | 無符號整數      | ``np.dtype('u1') == np.uint8``      |
| ``'f'``          | 浮點數        | ``np.dtype('f8') == np.int64``      |
| ``'c'``          | 複數 | ``np.dtype('c16') == np.complex128``|
| ``'S'``, ``'a'`` | 字符串                | ``np.dtype('S5')``                  |
| ``'U'``          | Unicode字符串       | ``np.dtype('U') == np.str_``        |
| ``'V'``          | 原始數據       | ``np.dtype('V') == np.void``        |

## More Advanced Compound Types

## 高級複合類型

> It is possible to define even more advanced compound types.
For example, you can create a type where each element contains an array or matrix of values.
Here, we'll create a data type with a ``mat`` component consisting of a $3\times 3$ floating-point matrix:

除此之外，還可以定義更加複雜的複合類型。例如，你可以創建一個類型，其中的每一個元素都是一個數組或矩陣。下面，創建一個數據類型內含一個`mat`對象，是一個$3\times 3$的浮點數矩陣：

In [13]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


> Now each element in the ``X`` array consists of an ``id`` and a $3\times 3$ matrix.
Why would you use this rather than a simple multidimensional array, or perhaps a Python dictionary?
The reason is that this NumPy ``dtype`` directly maps onto a C structure definition, so the buffer containing the array content can be accessed directly within an appropriately written C program.
If you find yourself writing a Python interface to a legacy C or Fortran library that manipulates structured data, you'll probably find structured arrays quite useful!

`X`數組中的每個元素都有一個`id`和一個$3\times 3$的矩陣。為什麼需要這樣用，為什麼不用一個多維數組或者甚至是Python的字典呢？原因是NumPy的`dtype`數據類型直接對應這一個C語言的結構體定義，因此存儲這個數組的內容內容可以直接被C語言的程序訪問到。如果你在寫訪問底層C語言或Fortran語言的Python接口的話，你會發現這種結構化數組很有用。

## RecordArrays: Structured Arrays with a Twist

## 記錄數組：物件導向的結構化數組

> NumPy also provides the ``np.recarray`` class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than as dictionary keys.
Recall that we previously accessed the ages by writing:

NumPy還提供了`np.recarray`對象，看起來基本和前面介紹的結構化數組相同，但是有一個額外的特性：字段不是使用字典關鍵字來訪問，而是使用屬性進行訪問。前面我們使用關鍵字來訪問數組的年齡字段：

In [14]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [15]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

> The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax. We can see this here:

這樣做的缺點是，當按照對象屬性來訪問數組數據時，會有額外的性能損耗。下面的例子可以看到：

In [16]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

92.3 ns ± 0.315 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
1.61 µs ± 9.42 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.13 µs ± 25.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


> Whether the more convenient notation is worth the additional overhead will depend on your own application.

是使用更方便簡潔的寫法還是使用更高性能的寫法，取決於你應用的需求。

<!--NAVIGATION-->
< [数组排序](02.08-Sorting.ipynb) | [目录](Index.ipynb) | [使用Pandas进行数据处理](03.00-Introduction-to-Pandas.ipynb) >

<a href="https://colab.research.google.com/github/wangyingsm/Python-Data-Science-Handbook/blob/master/notebooks/02.09-Structured-Data-NumPy.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
