## Casting
We cast NumPy arrays through their inherent astype function. The function's required argument is the new type for the array. It returns the array cast to the new type.

In [1]:
import numpy as np
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [2]:
np.array(list(range(10)), dtype=np.float64).astype(np.int32).dtype

dtype('int32')

In [3]:
array8 = np.array([3.5, -1.5, -2.5, 0.5, 12.6, 10.8])
array8

array([ 3.5, -1.5, -2.5,  0.5, 12.6, 10.8])

In [4]:
array9 = array8.astype(np.int64)
array9

array([ 3, -1, -2,  0, 12, 10])

In [5]:
num_strings = np.array(['1', '-2', '3', '4'], dtype=np.string_)
num_strings

array([b'1', b'-2', b'3', b'4'], dtype='|S2')

In [6]:
num_array_int32 = num_strings.astype(np.int32)
num_array_int32

array([ 1, -2,  3,  4], dtype=int32)

In [7]:
num_array_float = num_strings.astype(np.float)
num_array_float

/var/folders/9q/486czkcn7lv5v0hwbt71twdc0000gn/T/ipykernel_10658/4201449305.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  num_array_float = num_strings.astype(np.float)


array([ 1., -2.,  3.,  4.])

In [8]:
int_array = np.arange(15)
int_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
float_type = np.array([1.5, 1.7, 1.9, 1.11, 1.13], dtype=np.float64)
float_type

array([1.5 , 1.7 , 1.9 , 1.11, 1.13])

In [10]:
int_array_float = int_array.astype(float_type.dtype)
int_array_float

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [11]:
empty_uint64 = np.empty(3, dtype='u8')
empty_uint64

array([0, 1, 2], dtype=uint64)

## File Working with CSV

In [12]:
import numpy as np
new_data = np.random.random((50,4))
np.savetxt("output/Managing_Data_Files.csv", new_data, fmt="%.2f", delimiter=",", header = "H1, H2, H3, H4")

In [13]:
reading_csv = np.loadtxt("output/Managing_Data_Files.csv", delimiter=",")
reading_csv[:4,:]

array([[0.69, 0.47, 0.5 , 0.98],
       [0.99, 0.54, 0.1 , 0.9 ],
       [0.72, 0.73, 0.53, 0.67],
       [0.81, 0.38, 0.07, 0.65]])

** 1.2  Functions for creating arrays**

In [14]:
#create array using diag function
a = np.diag([1, 2, 3, 4]) #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [16]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 
a

array([0.09785076, 0.58178755, 0.49218559, 0.39527336])

In [17]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
a

array([-0.42409902,  2.19670184, -0.52946138, -1.72239552])

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

## Copies and Views

Similar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent copy function. The function has no required arguments, and it returns the copied array.

In the code example below, c is a reference to a while d is a copy. Therefore, changing c leads to the same change in a, while changing d does not change the value of b.

In [18]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = a[::2]   #### Creating a sub array with step size 2
b

array([0, 2, 4, 6, 8])

In [21]:
np.shares_memory(a, b)

True

In [22]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [23]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [24]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [25]:
np.shares_memory(a, c)

False

In [26]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Transposing
Similar to how it is common to reshape data, it is also common to transpose data. Perhaps we have data that's supposed to be in a particular format, but some new data we get is rearranged. We can just transpose the data, using the np.transpose function, to convert it to the proper format.

In [27]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


# Matrix multiplication
Since NumPy arrays are basically vectors and matrices, it makes sense that there are functions for dot products and matrix multiplication. Specifically, the main function to use is np.matmul, which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication.

The code below shows various examples of matrix multiplication. When both inputs are 1-D, the output is the dot product.

Note that the dimensions of the two input matrices must be valid for a matrix multiplication. Specifically, the second dimension of the first matrix must equal the first dimension of the second matrix, otherwise np.matmul will result in a ValueError.

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
#print(repr(np.matmul(arr3, arr3))) # This will result in ValueError

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


# Numerical Operation in Numpy

### Statistics

In [29]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [30]:
y.mean()

3.0

In [31]:
np.median(x)

1.5

In [32]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [33]:
x.std()          # full population standard dev.

0.82915619758885

In [34]:
y.std()

1.9148542155126762

## Funciones Universales Binarias

### Son funciones que realizan operaciones elemento-a-elemento sobre datos en una   `ndarray`.  Las funciones _binarias_ toman dos arrays y devuelven uno o más arrays.

|Función|Descripción|
|-------|-----------|
|`add`|Suma entre elementos correspondientes entre arrays|
|`subtract`|Resta entre elementos de arrays|
|`multiply`|Multiplica arrays|
|`divide`, `floor_divide`|Divide o división truncada|
|`array_equal`|Devuelve `True` si los elementos del array son iguales entre sí|
|`power`|Eleva cada elemento del primer array a la potencia indicada en el segundo array|
|`fmin`|Devuelve el mínimo entre cada elemento. `fmin` ignora los `NaN`|
|`fmax`|Devuelve el máximo entre cada elemento. `fmax` ignora los `NaN`|


In [35]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [36]:
np.add(arr,arr_2)
np.subtract(arr,arr_2)
np.multiply(arr,arr_2)
np.divide(arr,arr_2)
np.array_equal(arr,arr_2)
np.fmin(arr,arr_2)
np.fmax(arr,arr_2)

array([ 8, 36, 17, 19,  9])

In [37]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.42499228, 0.87660958, 0.09676212],
       [0.29748065, 0.4827976 , 0.63516339],
       [0.72660517, 0.0095114 , 0.85538767],
       [0.41777521, 0.07376987, 0.84014648]])

In [39]:
arr_ent = np.random.randint(100, size=(2,3))
arr_ent

array([[ 7, 69,  5],
       [19, 98, 37]])

In [40]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [41]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [42]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.delete(arr_ent,0,axis=1)

array([[69,  5],
       [98, 37]])

## # Mathematical and Statistical Methods

In [44]:
import numpy as np
data = np.random.randn(6, 3)
data

array([[-1.21813846,  0.70658907,  1.62137725],
       [ 0.64657389, -1.18859235, -0.28308148],
       [ 0.7053892 ,  1.30585619, -0.23397239],
       [-0.12276179, -3.17386678,  0.20871835],
       [ 0.08418209, -0.06043242,  0.16385678],
       [ 0.3553862 , -1.69352718, -0.45346825]])

In [45]:
data.mean()

-0.14610622688964517

In [46]:
data.min()

-3.1738667813789663

In [47]:
data.max()

1.621377254468465

In [48]:
data.sum()

-2.629912084013613

In [49]:
data.sum(axis = 0)

array([ 0.45063113, -4.10397348,  1.02343027])

## Values

In [50]:
values = np.arange(5)
values

array([0, 1, 2, 3, 4])

In [51]:
values.cumsum()

array([ 0,  1,  3,  6, 10])

In [52]:
values.std()

1.4142135623730951

In [53]:
matrix_array= np.array([np.arange(1, 5), np.arange(6, 10 ), np.arange(11, 15)])
matrix_array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [54]:
matrix_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 7,  9, 11, 13],
       [18, 21, 24, 27]])

In [55]:
matrix_array.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 6, 13, 21, 30],
       [11, 23, 36, 50]])

In [56]:
matrix_array.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    6,    42,   336,  3024],
       [   11,   132,  1716, 24024]])

#### Write a NumPy program to convert an array to a float type.
```
Original array 
[1, 2, 3, 4] 
Array converted to a float type: 
[ 1. 2. 3. 4.] 
```

In [57]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


#### Write a NumPy program to construct an array by repeating.
```
Original array 
[1, 2, 3, 4] 
Repeating 2 times 
[1 2 3 4 1 2 3 4]
Repeating 3 times 
[1 2 3 4 1 2 3 4 1 2 3 4]
```

In [58]:
n=3
x = np.tile(a, n)
x

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

#### How to tell if a given 2D array has null columns?

In [59]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("Test whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

[[2 2 1 1 2 0 0 2 0 0]
 [2 2 2 1 0 2 2 2 1 1]
 [0 1 1 2 2 0 1 0 1 1]
 [0 1 2 1 2 0 0 1 1 0]]
Test whether the said array has null columns or not:
False


#### Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
```
a= [
[1,2,3]
]

b= [
[4],
[5],
[6],
]

Expected Output = [[5 6 7]
                   [6 7 8]
                   [7 8 9]]
```


In [60]:
A = np.arange(1,4).reshape(3,1)
B = np.arange(4,7).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[5 6 7]
 [6 7 8]
 [7 8 9]]


##### Solve the linear equation
##### 10x+4y = 3 
#####  -x+5y = 2 

In [61]:
A = np.array([[10, 4], [-1, 5]])
b = np.array([3,2])
x = np.linalg.solve(A, b)
x

array([0.12962963, 0.42592593])

##### Create a 4x4 matrix with random values and find inverse of it.

In [62]:
x= np.random.random((4,4))
print(x)
print("Inverse")
y = np.linalg.inv(x) 
print(y)

[[0.91070189 0.6751822  0.25010643 0.29433468]
 [0.5548486  0.0440081  0.5397663  0.39656552]
 [0.29715829 0.87043343 0.55896829 0.82689248]
 [0.26596513 0.39568363 0.44805847 0.63174058]]
Inverse
[[ 1.35118458 -0.44364363 -2.13852767  2.44810255]
 [ 0.03962811  0.30860583  2.96047105 -4.08718023]
 [-1.99615951  4.77809228  5.54949906 -9.33314545]
 [ 0.82209061 -3.39535139 -4.88988092  9.73170866]]


##### Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

##### Expected Output:
#### Original Array:
```
['python' 'PHP' 'java' 'C++']

Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

```

In [63]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


/var/folders/9q/486czkcn7lv5v0hwbt71twdc0000gn/T/ipykernel_10658/3400659836.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)


##### Write a NumPy program to split the element of a given array with spaces
```
Original Array:
 ['apple mangoes peach grapes']
Output
[list(['apple', 'mangoes', 'peach', 'grapes'])]
```

In [64]:
x= np.array(['apple mangoes peach grapes'])
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)


Split the element of the said array with spaces: 
[list(['apple', 'mangoes', 'peach', 'grapes'])]


##### Write a NumPy program to flatten the array and then find its median.
```
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
```

In [65]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
flat=x.flatten()
print(flat)
np.median(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


5.5

##### Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
```
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
```

In [66]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.percentile(x,80,axis=1)

array([ 4., 10.])

In [67]:
import numpy as np
array_4 = np.array(list(range(10)))
array_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
array_5 = np.array(list(range(15)), dtype = np.int32)
array_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)