## Numpy Statistical Functions - Mode

In [1]:
import numpy as np
y = np.array([6, 6, 3, 8, 4, 6, 3, 2, 4, 2, 6, 8, 8, 6, 2])

In [2]:
from scipy import stats
result = stats.mode(y)
result

ModeResult(mode=array([6]), count=array([5]))

In [4]:
mode, count = stats.mode(y)
print('mode:',mode[0])
print('count:',count[0])

mode: 6
count: 5


In [5]:
#categorical string type example
y = np.array(["red", "blue", "blue", "red", "green", "red", "red"])

In [6]:
mode, count =stats.mode(y)
print('mode:',mode[0])
print('count:',count[0])

mode: red
count: 4


2D Array

In [7]:
np.random.seed(12)
x= np.random.randint(low=52,high=60,size=(8,6))
x

array([[55, 55, 58, 57, 53, 54],
       [55, 55, 56, 52, 58, 53],
       [56, 57, 57, 53, 54, 55],
       [58, 54, 52, 57, 52, 56],
       [57, 54, 53, 55, 58, 56],
       [55, 53, 58, 59, 59, 52],
       [54, 58, 54, 52, 56, 58],
       [55, 57, 53, 57, 58, 52]])

###### axis = 0

In [8]:
mode,count = stats.mode(x,axis=0)
print(mode)
print(count)

[[55 54 53 57 58 52]]
[[4 2 2 3 3 2]]


In [9]:
#to get 1D result, get element at row index 0
print('mode:',mode[0])
print('frequency:',count[0])

mode: [55 54 53 57 58 52]
frequency: [4 2 2 3 3 2]


In [10]:
#to access specific column
print('mode for col 3:',mode[0,3])
print('frequency for col 3:',count[0,3])

mode for col 3: 57
frequency for col 3: 3


###### axis = 1

In [11]:
x

array([[55, 55, 58, 57, 53, 54],
       [55, 55, 56, 52, 58, 53],
       [56, 57, 57, 53, 54, 55],
       [58, 54, 52, 57, 52, 56],
       [57, 54, 53, 55, 58, 56],
       [55, 53, 58, 59, 59, 52],
       [54, 58, 54, 52, 56, 58],
       [55, 57, 53, 57, 58, 52]])

In [12]:
mode,count = stats.mode(x,axis=1)
print(mode)
print(count)

[[55]
 [55]
 [57]
 [52]
 [53]
 [59]
 [54]
 [57]]
[[2]
 [2]
 [2]
 [2]
 [1]
 [2]
 [2]
 [2]]


In [13]:
#to get 1D result, get element at column index 0
print(mode[:,0])
print(count[:,0])

[55 55 57 52 53 59 54 57]
[2 2 2 2 1 2 2 2]


In [14]:
#to access specific row
print('mode for row 3:',mode[3,0])
print('frequency for row 3:',count[3,0])

mode for row 3: 52
frequency for row 3: 2


###### Multimode

In [15]:
x = np.array([5,5,5,8,18,18,18,25,35,46])

In [16]:
#note: when there is multimode, scipy stats 
#return the smallest element as mode.
z = stats.mode(x)
z

ModeResult(mode=array([5]), count=array([3]))

code to return multi mode values

In [17]:
#create frequency table using numpy unique()
values, counts = np.unique(x, return_counts=True)
print('values:',values)
print('counts:',counts)

values: [ 5  8 18 25 35 46]
counts: [3 1 3 1 1 1]


In [18]:
#filter values whose corresponding counts 
#matches with the maximum value of count
mode = values[counts == np.max(counts)]
print(mode) 

[ 5 18]


###### No Mode

In [19]:
x = np.array([5, 8, 18, 25, 35, 46])

In [20]:
#note: when there is no mode also, scipy stats 
#return the smallest element as mode.
z = stats.mode(x)
z

ModeResult(mode=array([5]), count=array([1]))

code to return empty array when there is no mode

In [21]:
#get the frequency table first using unique() function
values, counts = np.unique(x, return_counts=True)
print('values:',values)
print('counts:',counts)

values: [ 5  8 18 25 35 46]
counts: [1 1 1 1 1 1]


In [22]:
#check whether all of them have same frequency
#we can do this by checking whether maximum and minimum frequency are equal
if np.max(counts)==np.min(counts):
    mode = np.array([])
else:
    #if they has mode, then return mode or multimodes 
    mode = values[counts == np.max(counts)]
    
print(mode)

[]


In [23]:
#custom mode function that also handles no mode and multi mode cases
def mode_cust(arr):
    values, counts = np.unique(arr, return_counts=True)
    if np.max(counts)==np.min(counts): #check for  no mode case
        mode = np.array([])
    else:
        #if data has mode, then return single mode or multimodes 
        mode = values[counts == np.max(counts)]
    return mode

In [24]:
#check custom mode function for no mode case
x = np.array([5, 8, 18, 25, 35, 46])
mode_cust(x)

array([], dtype=float64)

In [25]:
#check custom mode function for multi mode case
x = np.array([5,5,5,8,18,18,18,25,35,46])
mode_cust(x)

array([ 5, 18])

In [26]:
#check custom mode function for single mode case
x = np.array([6, 6, 3, 8, 4, 6, 3, 2, 4, 2, 6, 8, 8, 6, 2])
mode_cust(x)

array([6])