## function

In [ ]:
import numpy as np
arr=np.ones(2)
arr

In [ ]:
np.ones((2,2))

In [ ]:
np.zeros(2)

In [ ]:
np.zeros((2,2))

In [ ]:
np.eye(2,2)

In [ ]:
arr=np.array([1.432, 3.087, 4.56])
np.around(arr)

In [ ]:
np.around(arr,2)

In [ ]:
np.linspace(0,10,5)

In [ ]:
import numpy as np

print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4)
print(subArrays)

In [ ]:

import numpy as np

print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

In [ ]:
faces = np.random.randint(0,100,(10,3))
print(f'Set of 10 triplets\n\n{faces}')
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(f'\nUnique line segments composing all the triangles\n\n{G}')

###  Numpy Exercise

#### 1. Import the numpy package under the name np

In [ ]:
import numpy as np

#### 2. Create a numpy array of size 15 initialsed to zero.

In [ ]:
zeros=np.zeros(15)
zeros

#### 3. Create a numpy array of size 10 initiased to -1 but the fifth value which is 1

In [ ]:
numpy_array=np.full(10,-1)
print(numpy_array)

numpy_array[4]=1
print(numpy_array)

#### 4. Create a array with values ranging from 10 to 49 which are multiple of 3

In [ ]:
arr=np.arange(12,50,3)
arr

#### 5. Create and array with values ranging from 1 to 10 and Reverse the array (first element becomes last)

In [ ]:
np_arr=np.arange(1,11)
np_arr[::-1]

#### 6. Create a 10x10 array with random values with seed value 7 and find the minimum and maximum values for each row.

In [ ]:
np.random.seed(7)
x = np.random.random((10,10))
min_per_row=x.min(axis=1)
max_per_row=x.max(axis=1)

#### 7. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
```

a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
b=[[1,2],[3,4],[5,6]]

```

In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=np.array([[1,2],[3,4],[5,6]])
np.matmul(a,b)

#### 8. Given a 1D array, negate all elements which are between 3 and 8..And reshape to 3x5 shape
```
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
```

In [ ]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a[(3 < a) & (a < 8)] *= -1
print(a)
reshaped_a = a.reshape(3,5)
print(reshaped_a)

#### 9. Create a 5x5 matrix with row values ranging from 0 to 4. Pad this 2D array with zero all around the border
#### Expected Output :
```
[
[0,0,0,0,0,0,0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0,0,0,0,0,0,0]
]
```

In [ ]:
x = np.zeros((5,5))
y= np.arange(5)
original=x+y
print(original)

# Create zeros col and row to append.
zeros_row=np.zeros(7,dtype=int).reshape(1,7)
zeros_col=np.zeros(5,dtype=int).reshape(5,1)

# append using vstack and hstack
padded=np.hstack((zeros_col,original,zeros_col))
padded=np.vstack((zeros_row,padded,zeros_row))
print(padded)

# Numpy also provide pad function 
print("Alternate Solution")
alternate = np.pad(original, pad_width=1, mode='constant', constant_values=0)
print(alternate)

#### 10. Read the following from file and fill missing values with 0
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt("a.txt",dtype=int,filling_values=0.0)

#### 11.  Given a array arr. Write a NumPy program to test element-wise for NaN of a given array.
```
arr = np.array([1, 0, np.nan, np.inf])
```

In [ ]:
arr = np.array([1, 0, np.nan, np.inf])
print(np.isnan(arr))

#### 12. Write a NumPy program to convert an array to a float type.
```
Original array 
[1, 2, 3, 4] 
Array converted to a float type: 
[ 1. 2. 3. 4.] 
```

In [ ]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

#### 13.  Write a NumPy program to construct an array by repeating.
```
Original array 
[1, 2, 3, 4] 
Repeating 2 times 
[1 2 3 4 1 2 3 4]
Repeating 3 times 
[1 2 3 4 1 2 3 4 1 2 3 4]
```

In [ ]:
n=3
x = np.tile(a, n)
x

#### 14. How to tell if a given 2D array has null columns?

In [ ]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("Test whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

#### 15. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
```
a= [
[1,2,3]
]

b= [
[4],
[5],
[6],
]

Expected Output = [[5 6 7]
                   [6 7 8]
                   [7 8 9]]
```


In [ ]:
A = np.arange(1,4).reshape(3,1)
B = np.arange(4,7).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

##### 16. Solve the linear equation
##### 10x+4y = 3 
#####  -x+5y = 2 

In [ ]:
A = np.array([[10, 4], [-1, 5]])
b = np.array([3,2])
x = np.linalg.solve(A, b)
x

##### 17. Create a 4x4 matrix with random values and find inverse of it.

In [ ]:
x= np.random.random((4,4))
print(x)
print("Inverse")
y = np.linalg.inv(x) 
print(y)

##### 18.  Consider following array replace every 3 with 0
```
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
```

In [ ]:
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

array[(array == 3)] =0
array

##### 19. Considering these numpy array of person names and corresponding arrays for their age and gender. Findout names Who’s at least 44 in age.?
```
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])
```

In [ ]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

name= names[(ages >= 44)]
print(name)

###### 20. Based on above array. Which males are over 42?.

In [ ]:
name= names[(ages > 42) & (genders == 'male')]
print(name)

###### 21. Based on above array. Who’s a not a male or who is younger than 45? 

In [ ]:
name= names[(ages < 45) & (genders != 'male')]
name

##### 22. Given the following pairs of array-shapes, determine what the resulting broadcasted shapes will be.
##### Indicate if a pair is broadcast-incompatible.
```
1.    7 x 2 with 7
2.    4 with 3 x 4
3.    1 x 3 x 1 with 8 x 1 x 1
4.    9 x 2 x 5 with 2 x 5
5.    3 with 3 x 3 x 2 
```

```
Answer:
1. broadcast-incompatible
2. (3 x 4)
3. (8 x 3 x 1)
4. (9 x 2 x 5)
5. broadcast-incompatible
```

##### 23. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

##### Expected Output:
#### Original Array:
```
['python' 'PHP' 'java' 'C++']

Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

```

In [ ]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

##### 24. Write a NumPy program to split the element of a given array with spaces
```
Original Array:
 ['apple mangoes peach grapes']
Output
[list(['apple', 'mangoes', 'peach', 'grapes'])]
```

In [ ]:
x= np.array(['apple mangoes peach grapes'])
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

##### 25. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array
```
Original array:
[[10 40]
[30 20]]
Sort the array along the first axis:
[[10 20]
[30 40]]
Sort the array along the last axis:
[[10 40]
[20 30]]
Sort the flattened array:
[10 20 30 40] 
```

In [ ]:
x= np.array([[10,40],[30,20]])
print(x)
y=np.sort(x,axis=0)
print(y)
z=np.sort(x,axis=1)
print(z)
k=np.sort(x.flatten())
print(k)

##### 26. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
``` 
a= [1,3,5,6,7,8,9]
b= [10,11,23,45,67,12,13]
```

In [ ]:
a= np.array([1,3,5,6,7,8,9])
b= np.array([10,11,23,45,67,12,13])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

##### 27. Write a NumPy program to get the powers of 3 of an array values element-wise
```
a= [0 1 2 3 4 5 6]   
```

In [ ]:
a= np.array([0,1,2,3,4,5,6])
print(a**3)

###### 28. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
```
[[0 1 2 3 4 5 6]
[2 3 4 5 6 7 8]]
Maximum value along the second axis:
[6 8]
Minimum value along the second axis:
[0 2]
```

In [ ]:
x= np.array([[0,1,2,3,4,5,6],[2,3,4,5,6,7,8]])
print(x.max(axis=1))
print(x.min(axis=1))

##### 29. Write a NumPy program to flatten the array and then find its median.
```
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
flat=x.flatten()
print(flat)
np.median(flat)

##### 30. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
```
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.percentile(x,80,axis=1)

In [ ]:
%time for i in range(10): 
    my_array1 = array1*2

In [ ]:
%time for i in range(10): 
    my_array2 = [x*2 for x in array2]

In [ ]:
import numpy as np
array_4 = np.array(list(range(10)))
array_44


In [ ]:
np.array(list(range(10)), dtype=np.float64)

In [ ]:
array_5 = np.array(list(range(15)), dtype = np.int32)
array_5

In [ ]:
np.array(list(range(10)), dtype=np.float64).dtype

In [ ]:
array_6 = array_4.astype(np.float64)
print(array_6)
print(array_6.dtype)

In [ ]:
np.array(list(range(10)), dtype=np.float64).astype(np.int32).dtype

In [ ]:
array8 = np.array([3.5, -1.5, -2.5, 0.5, 12.6, 10.8])
array8

In [ ]:
array9 = array8.astype(np.int64)
array9

In [ ]:
num_strings = np.array(['1', '-2', '3', '4'], dtype=np.string_)
num_strings

In [ ]:
num_array_int32 = num_strings.astype(np.int32)
num_array_int32

In [ ]:
num_array_float = num_strings.astype(np.float)
num_array_float

In [ ]:
int_array = np.arange(15)
int_array

In [ ]:
float_type = np.array([1.5, 1.7, 1.9, 1.11, 1.13], dtype=np.float64)
float_type

In [ ]:
int_array_float = int_array.astype(float_type.dtype)
int_array_float

In [ ]:
empty_uint64 = np.empty(3, dtype='u8')
empty_uint64

## File

In [1]:
## Working with CSV

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
new_data = np.random.random((50,4))
np.savetxt("output/Managing_Data_Files.csv", new_data, fmt="%.2f", delimiter=",", header = "H1, H2, H3, H4")

In [ ]:
reading_csv = np.loadtxt("output/Managing_Data_Files.csv", delimiter=",")
reading_csv[:4,:]

** 1.2  Functions for creating arrays**

In [52]:
#using arrange function arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 10, 2) #start, end (exclusive), step
b

array([1, 3, 5, 7, 9])

In [ ]:
a = np.linspace(0, 1, 6) #start, end, number of points
a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [ ]:
a = np.ones((3, 3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [53]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0
d

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [ ]:
#create array using diag function
a = np.diag([1, 2, 3, 4]) #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
np.diag(a)   #Extract diagonal

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [55]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 
a

array([0.67270931, 0.26165094, 0.59989432, 0.24309559])

In [56]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
a

array([ 0.70266615, -0.17217638,  2.28855271,  0.03413919])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [57]:
a = np.arange(10)
a.dtype

dtype('int32')

In [ ]:
#You can explicitly specify which data-type you want:
a = np.arange(10, dtype='float64')
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
#The default data type is float for zeros and ones function
a = np.zeros((3, 3))
print(a)
a.dtype

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


dtype('float64')

**other datatypes**

In [58]:
d = np.array([1+2j, 2+4j])   #Complex datatype
print(d.dtype)

complex128


In [59]:
b = np.array([True, False, True, False])  #Boolean datatype
print(b.dtype)

bool


In [60]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [61]:
a = np.arange(10)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [63]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [65]:
a[2, 1] = 5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [66]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [68]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [69]:
# For reversing the string using this function
b = np.arange(5)
a = b[::-1] 
a

array([4, 3, 2, 1, 0])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b = a[::2]   #### Creating a sub array with step size 2
b

array([0, 2, 4, 6, 8])

In [72]:
np.shares_memory(a, b)

True

In [73]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [74]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [75]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [76]:
np.shares_memory(a, c)

False

In [77]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [78]:
a = np.random.randint(0, 20, 15)
a

array([ 9, 19,  9,  0,  6, 12, 19,  7, 10,  5, 16,  0, 14, 18,  0])

In [79]:
mask = (a % 2 == 0)         ### To writien a only even number we can used this operation 

In [80]:
extract_from_a = a[mask]
extract_from_a

array([ 0,  6, 12, 10, 16,  0, 14, 18,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [81]:
a[mask] = -1
a

array([ 9, 19,  9, -1, -1, -1, 19,  7, -1,  5, -1, -1, -1, -1, -1])

**Indexing with an array of integers**

In [82]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned 
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Numerical Operation in Numpy

## Elementwise Operations

### 1. Basic Operations

#### with scalars

In [84]:
a = np.array([1, 2, 3, 4]) #create an array
a + 1

array([2, 3, 4, 5])

In [85]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

#### All arithmetic operates elementwise

In [87]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [88]:
a * b

array([2., 4., 6., 8.])

In [9]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])
print(c * c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


#### comparisions operation

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [90]:
a > b

array([False, False,  True, False])

In [91]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [92]:
np.array_equal(a, c)

True

#### Logical Operations

In [93]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [94]:
np.logical_and(a, b)

array([ True, False, False, False])

In [96]:
a = np.arange(40)

np.sin(a)  

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [97]:
np.log(a)

C:\Users\khana\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [98]:
np.exp(a)   #evaluates e^x for each element in a given input

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16])

## Basic Reductions
###computing sums

In [101]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [102]:
#sum by rows and by columns
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [103]:
x.sum(axis=0)   #columns first dimension Axis  = 0 perform column vise operation

array([3, 3])

In [104]:
x.sum(axis=1)  #rows (second dimension)     Axis  = 1 perform column row  operation 

array([2, 4])

# Other reductions

In [105]:
x = np.array([1, 3, 2])
x.min()

1

In [106]:
x.max()

3

In [107]:
x.argmin()# index of minimum element

0

In [108]:
x.argmax()# index of maximum element

1

## Logical Operations

In [109]:
np.all([True, True, False])    ## If any one is False then is writen as false

False

In [110]:
np.any([True, False, False])         ##   If any one is true is writen as True

True

In [111]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [33]:
np.all(a == a)

True

In [113]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

### Statistics

In [114]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [115]:
y.mean()

3.0

In [116]:
np.median(x)

1.5

In [117]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [118]:
x.std()          # full population standard dev.

0.82915619758885

In [119]:
y.std()

1.9148542155126762

## Funciones Universales Binarias

### Son funciones que realizan operaciones elemento-a-elemento sobre datos en una   `ndarray`.  Las funciones _binarias_ toman dos arrays y devuelven uno o más arrays.

|Función|Descripción|
|-------|-----------|
|`add`|Suma entre elementos correspondientes entre arrays|
|`subtract`|Resta entre elementos de arrays|
|`multiply`|Multiplica arrays|
|`divide`, `floor_divide`|Divide o división truncada|
|`array_equal`|Devuelve `True` si los elementos del array son iguales entre sí|
|`power`|Eleva cada elemento del primer array a la potencia indicada en el segundo array|
|`fmin`|Devuelve el mínimo entre cada elemento. `fmin` ignora los `NaN`|
|`fmax`|Devuelve el máximo entre cada elemento. `fmax` ignora los `NaN`|


In [1]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [ ]:
np.add(arr,arr_2)
np.subtract(arr,arr_2)
np.multiply(arr,arr_2)
np.divide(arr,arr_2)
np.array_equal(arr,arr_2)
np.fmin(arr,arr_2)
np.fmax(arr,arr_2)

In [2]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.73101518, 0.91337663, 0.76844006],
       [0.8147712 , 0.18125237, 0.94750742],
       [0.66103443, 0.39113554, 0.91440374],
       [0.94634361, 0.30396435, 0.64538481]])

In [4]:
arr_ent = np.random.randint(100, size=(2,3))
arr_ent

array([[89, 85, 23],
       [21, 41, 93]])

In [5]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [6]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [7]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.delete(arr_ent,0,axis=1)

array([[85, 23],
       [41, 93]])

## # Mathematical and Statistical Methods

In [1]:
import numpy as np
data = np.random.randn(6, 3)
data

array([[ 1.1524977 ,  0.00419764,  1.78043853],
       [-2.07329943, -0.97366463,  0.11166521],
       [ 0.22991364, -0.86281024, -0.18513811],
       [ 1.706981  , -1.33787614, -1.00465309],
       [-1.41067229,  0.01500831, -2.16470453],
       [ 1.59715899, -0.37794744,  0.55625349]])

In [2]:
data.mean()

-0.17981396602535935

In [3]:
data.min()

-2.164704526378289

In [4]:
data.max()

1.780438530046246

In [5]:
data.sum()

-3.236651388456468

In [6]:
data.sum(axis = 0)

array([ 1.2025796, -3.5330925, -0.9061385])

## Values

In [8]:
values = np.arange(5)
values

array([0, 1, 2, 3, 4])

In [9]:
values.cumsum()

array([ 0,  1,  3,  6, 10])

In [10]:
values.std()

1.4142135623730951

In [11]:
matrix_array= np.array([np.arange(1, 5), np.arange(6, 10 ), np.arange(11, 15)])
matrix_array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [12]:
matrix_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 7,  9, 11, 13],
       [18, 21, 24, 27]])

In [13]:
matrix_array.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 6, 13, 21, 30],
       [11, 23, 36, 50]])

In [14]:
matrix_array.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    6,    42,   336,  3024],
       [   11,   132,  1716, 24024]])