## Numpy Statistical Functions - Median

### <center>Formula to compute Median</center>
## $$Median = \{\frac{(n + 1)}{2}\}^{th} term  $$
<center><i> n: no.of observations <br> </i></center>

In [1]:
import numpy as np
y = np.array([54, 48, 62, 42, 12, 52, 25, 37, 57])
np.median(y)

48.0

even number of elements

### <center>Formula to compute Median</center>
## $$Median = \frac {\left( \frac{n}{2} \right)^{th} term + \{ \left( \frac{n}{2} \right) + 1 \}^{th} term } {2} $$
<center><i> n: no.of observations <br> </i></center>

In [2]:
y = np.array([54, 48, 62, 42, 12, 52, 25, 37, 57, 400])
np.median(y)

50.0

2D array

In [3]:
x = np.array([[14, 17, 12, 33, 44],   
       [23, 6, 54, 8, 4],  
       [15, 2, 27, 1, 19, ]])

In [4]:
# The below code is used only for display purposes for training 
# and is not mandatory for learning numpy
from IPython.display import HTML, display

def display_table(data,size='h2'):
    html = "<table>"
    for row in data:
        html += "<tr>"
        for field in row:
            html += "<td><%s>%s</h2><td>"%(size,field)
        html += "</tr>"
    html += "</table>"
    display(HTML(html))

In [5]:
x

array([[14, 17, 12, 33, 44],
       [23,  6, 54,  8,  4],
       [15,  2, 27,  1, 19]])

###### axis=0

In [6]:
np.median(x,axis=0)

array([15.,  6., 27.,  8., 19.])

In [7]:
#the below code is only for understanding purposes
# and not required for computing median
temp = np.sort(x,axis=0)
print('sorted data for axis=0')
display_table(temp)

sorted data for axis=0


###### axis=1

In [8]:
x

array([[14, 17, 12, 33, 44],
       [23,  6, 54,  8,  4],
       [15,  2, 27,  1, 19]])

In [9]:
np.median(x,axis=1)

array([17.,  8., 15.])

In [10]:
#the below code is only for understanding purposes
# and not required for computing median
temp =np.sort(x,axis=1)
print('sorted data for axis=1')
display_table(temp)

sorted data for axis=1


In [11]:
#when axis=None
np.median(x)

15.0

In [12]:
#the below code is only for understanding purposes
# and not required for computing median
temp =np.array([ 1,  2,  4,  6,  8, 12, 14, 15, 17, 19, 23, 27, 33, 44, 54])
temp

array([ 1,  2,  4,  6,  8, 12, 14, 15, 17, 19, 23, 27, 33, 44, 54])