## Numpy Statistical Functions - Simple Functions

In [1]:
import numpy as np
y = np.array([6, 12, 8, 4, 15, 52,7])

In [2]:
#compute total of all elements
np.sum(y)

104

In [3]:
np.min(y)

4

In [4]:
np.max(y)

52

In [5]:
#alternate method to compute statistical functions using object function
y.sum()

104

<u>Difference between numpy package statistical functions and object functions </u><br>
Numpy package functions would work even for list type while one cannot invoke statistical functions on list object

In [6]:
l1 = [35, 78, 25]
np.sum(l1)

138

In [7]:
y

array([ 6, 12,  8,  4, 15, 52,  7])

In [8]:
#to find the index of the minimum element in array
np.argmin(y)

3

In [9]:
y[np.argmin(y)]

4

In [10]:
#to find the index of the maximum element in array
np.argmax(y)

5

In [11]:
y[np.argmax(y)]

52

2D Array

In [12]:
x = np.array([[20,1,18,26],[12,7,22,9],[25,31,16,14]])
print(x)

[[20  1 18 26]
 [12  7 22  9]
 [25 31 16 14]]


In [13]:
#sum along rows
np.sum(x,axis=0)

array([57, 39, 56, 49])

In [14]:
#sum along columns
np.sum(x,axis=1)

array([65, 50, 86])

In [15]:
#sum up entire 2D array
np.sum(x,axis=None)

201

In [16]:
#simple way to achieve above result
np.sum(x)

201

<u>Note on axis: </u> <br>
Axis 0 refers to vertical direction across rows. Hence it collapses rows and provide single statistical value for every column <br> 
Axis 1 refers to horizontal direction across columns. Hence it collapses columns and provide single statistical value for every row

In [17]:
x

array([[20,  1, 18, 26],
       [12,  7, 22,  9],
       [25, 31, 16, 14]])

In [18]:
np.min(x,axis=0)

array([12,  1, 16,  9])

In [19]:
np.min(x,axis=1)

array([ 1,  7, 14])

In [20]:
np.min(x)

1

In [21]:
x

array([[20,  1, 18, 26],
       [12,  7, 22,  9],
       [25, 31, 16, 14]])

In [22]:
np.max(x,axis=0)

array([25, 31, 22, 26])

In [23]:
np.max(x,axis=1)

array([26, 22, 31])

In [24]:
np.max(x)

31

In [25]:
x

array([[20,  1, 18, 26],
       [12,  7, 22,  9],
       [25, 31, 16, 14]])

In [26]:
np.argmin(x,axis=0)

array([1, 0, 2, 1])

In [27]:
np.argmin(x,axis=1)

array([1, 1, 3])

In [28]:
x

array([[20,  1, 18, 26],
       [12,  7, 22,  9],
       [25, 31, 16, 14]])

In [29]:
np.argmax(x,axis=0)

array([2, 2, 1, 0])

In [30]:
np.argmax(x,axis=1)

array([3, 2, 1])

###### Formula: Maximum - Minimum

In [1]:
import numpy as np

1D Array

In [2]:
y = np.array([25, 17, 35, 21, 16, 34, 10])

In [3]:
np.max(y) - np.min(y)

25

In [4]:
np.ptp(y)

25

The name of the function <b>"ptp"</b> comes from the acronym for ‘peak to peak’.

2D Array

In [5]:
np.random.seed(5)
x= np.random.randint(low=15,high=100,size=(7,4))
x

array([[93, 76, 31, 88],
       [23, 77, 42, 45],
       [95, 22, 91, 30],
       [68, 95, 42, 59],
       [92, 90, 80, 62],
       [45, 99, 33, 24],
       [56, 77, 16, 97]])

In [6]:
#compute range across rows
np.ptp(x,axis=0)

array([72, 77, 75, 73])

In [7]:
np.ptp(x,axis=1)

array([62, 54, 73, 53, 30, 75, 81])

In [8]:
np.ptp(x)

83