## Creating 1-D array

In [ ]:
import numpy as np
ar=np.array([1,4,6,3,7])
ar

In [ ]:
ar=np.array([1,4,6,3,7])
ar[2]

In [ ]:
ar1=np.array((2,3,4,5))
ar1

## Creating 2-D array

In [ ]:
arr=np.array([[1,2,4], [5,6,8]])
arr

In [ ]:
arr=np.array([[1,2,4], [5,6,8]])
arr[0,1]

## Creating 3-D array

In [ ]:
arr=np.array([[[1,2,3], [5,6,7]], [[1,2,3], [5,6,7]]])
arr

## Unary Operations

In [ ]:
import numpy as np
arr=np.array([1,3,5,2,6])
np.cos(arr)

In [ ]:
np.log(arr)

In [ ]:
np.mean(arr)

In [ ]:
np.median(arr)

In [ ]:
np.std(arr)

In [ ]:
np.exp(arr)

## Binary Operations

In [ ]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])

arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
arr1*arr2

## function

In [ ]:
import numpy as np
arr=np.ones(2)
arr

In [ ]:
np.ones((2,2))

In [ ]:
np.zeros(2)

In [ ]:
np.zeros((2,2))

In [ ]:
np.eye(2,2)

In [ ]:
arr=np.array([1.432, 3.087, 4.56])
np.around(arr)

In [ ]:
np.around(arr,2)

In [ ]:
np.linspace(0,10,5)

In [ ]:
import numpy as np

print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4)
print(subArrays)

In [ ]:

import numpy as np

print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

In [ ]:
faces = np.random.randint(0,100,(10,3))
print(f'Set of 10 triplets\n\n{faces}')
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(f'\nUnique line segments composing all the triangles\n\n{G}')

## Unary Operations

In [ ]:
import numpy as np
arr=np.array([1,3,5,2,6])
np.cos(arr)

In [ ]:
np.log(arr)

In [ ]:
np.mean(arr)

In [ ]:
np.median(arr)

In [ ]:
np.std(arr)

In [ ]:
np.exp(arr)

## Binary Operations

In [ ]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])
arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
arr1*arr2

In [ ]:
import numpy as np
np.linspace(0,10,5)

###  Numpy Exercise

#### 1. Import the numpy package under the name np

In [ ]:
import numpy as np

#### 2. Create a numpy array of size 15 initialsed to zero.

In [ ]:
zeros=np.zeros(15)
zeros

#### 3. Create a numpy array of size 10 initiased to -1 but the fifth value which is 1

In [ ]:
numpy_array=np.full(10,-1)
print(numpy_array)

numpy_array[4]=1
print(numpy_array)

#### 4. Create a array with values ranging from 10 to 49 which are multiple of 3

In [ ]:
arr=np.arange(12,50,3)
arr

#### 5. Create and array with values ranging from 1 to 10 and Reverse the array (first element becomes last)

In [ ]:
np_arr=np.arange(1,11)
np_arr[::-1]

#### 6. Create a 10x10 array with random values with seed value 7 and find the minimum and maximum values for each row.

In [ ]:
np.random.seed(7)
x = np.random.random((10,10))
min_per_row=x.min(axis=1)
max_per_row=x.max(axis=1)

#### 7. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
```

a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
b=[[1,2],[3,4],[5,6]]

```

In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=np.array([[1,2],[3,4],[5,6]])
np.matmul(a,b)

#### 8. Given a 1D array, negate all elements which are between 3 and 8..And reshape to 3x5 shape
```
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
```

In [ ]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a[(3 < a) & (a < 8)] *= -1
print(a)
reshaped_a = a.reshape(3,5)
print(reshaped_a)

#### 9. Create a 5x5 matrix with row values ranging from 0 to 4. Pad this 2D array with zero all around the border
#### Expected Output :
```
[
[0,0,0,0,0,0,0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0,0,0,0,0,0,0]
]
```

In [ ]:
x = np.zeros((5,5))
y= np.arange(5)
original=x+y
print(original)

# Create zeros col and row to append.
zeros_row=np.zeros(7,dtype=int).reshape(1,7)
zeros_col=np.zeros(5,dtype=int).reshape(5,1)

# append using vstack and hstack
padded=np.hstack((zeros_col,original,zeros_col))
padded=np.vstack((zeros_row,padded,zeros_row))
print(padded)

# Numpy also provide pad function 
print("Alternate Solution")
alternate = np.pad(original, pad_width=1, mode='constant', constant_values=0)
print(alternate)

#### 10. Read the following from file and fill missing values with 0
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt("a.txt",dtype=int,filling_values=0.0)

#### 11.  Given a array arr. Write a NumPy program to test element-wise for NaN of a given array.
```
arr = np.array([1, 0, np.nan, np.inf])
```

In [ ]:
arr = np.array([1, 0, np.nan, np.inf])
print(np.isnan(arr))

#### 12. Write a NumPy program to convert an array to a float type.
```
Original array 
[1, 2, 3, 4] 
Array converted to a float type: 
[ 1. 2. 3. 4.] 
```

In [ ]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

#### 13.  Write a NumPy program to construct an array by repeating.
```
Original array 
[1, 2, 3, 4] 
Repeating 2 times 
[1 2 3 4 1 2 3 4]
Repeating 3 times 
[1 2 3 4 1 2 3 4 1 2 3 4]
```

In [ ]:
n=3
x = np.tile(a, n)
x

#### 14. How to tell if a given 2D array has null columns?

In [ ]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("Test whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

#### 15. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
```
a= [
[1,2,3]
]

b= [
[4],
[5],
[6],
]

Expected Output = [[5 6 7]
                   [6 7 8]
                   [7 8 9]]
```


In [ ]:
A = np.arange(1,4).reshape(3,1)
B = np.arange(4,7).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

##### 16. Solve the linear equation
##### 10x+4y = 3 
#####  -x+5y = 2 

In [ ]:
A = np.array([[10, 4], [-1, 5]])
b = np.array([3,2])
x = np.linalg.solve(A, b)
x

##### 17. Create a 4x4 matrix with random values and find inverse of it.

In [ ]:
x= np.random.random((4,4))
print(x)
print("Inverse")
y = np.linalg.inv(x) 
print(y)

##### 18.  Consider following array replace every 3 with 0
```
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
```

In [ ]:
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

array[(array == 3)] =0
array

##### 19. Considering these numpy array of person names and corresponding arrays for their age and gender. Findout names Who’s at least 44 in age.?
```
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])
```

In [ ]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

name= names[(ages >= 44)]
print(name)

###### 20. Based on above array. Which males are over 42?.

In [ ]:
name= names[(ages > 42) & (genders == 'male')]
print(name)

###### 21. Based on above array. Who’s a not a male or who is younger than 45? 

In [ ]:
name= names[(ages < 45) & (genders != 'male')]
name

##### 22. Given the following pairs of array-shapes, determine what the resulting broadcasted shapes will be.
##### Indicate if a pair is broadcast-incompatible.
```
1.    7 x 2 with 7
2.    4 with 3 x 4
3.    1 x 3 x 1 with 8 x 1 x 1
4.    9 x 2 x 5 with 2 x 5
5.    3 with 3 x 3 x 2 
```

```
Answer:
1. broadcast-incompatible
2. (3 x 4)
3. (8 x 3 x 1)
4. (9 x 2 x 5)
5. broadcast-incompatible
```

##### 23. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

##### Expected Output:
#### Original Array:
```
['python' 'PHP' 'java' 'C++']

Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

```

In [ ]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

##### 24. Write a NumPy program to split the element of a given array with spaces
```
Original Array:
 ['apple mangoes peach grapes']
Output
[list(['apple', 'mangoes', 'peach', 'grapes'])]
```

In [ ]:
x= np.array(['apple mangoes peach grapes'])
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

##### 25. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array
```
Original array:
[[10 40]
[30 20]]
Sort the array along the first axis:
[[10 20]
[30 40]]
Sort the array along the last axis:
[[10 40]
[20 30]]
Sort the flattened array:
[10 20 30 40] 
```

In [ ]:
x= np.array([[10,40],[30,20]])
print(x)
y=np.sort(x,axis=0)
print(y)
z=np.sort(x,axis=1)
print(z)
k=np.sort(x.flatten())
print(k)

##### 26. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
``` 
a= [1,3,5,6,7,8,9]
b= [10,11,23,45,67,12,13]
```

In [ ]:
a= np.array([1,3,5,6,7,8,9])
b= np.array([10,11,23,45,67,12,13])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

##### 27. Write a NumPy program to get the powers of 3 of an array values element-wise
```
a= [0 1 2 3 4 5 6]   
```

In [ ]:
a= np.array([0,1,2,3,4,5,6])
print(a**3)

###### 28. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
```
[[0 1 2 3 4 5 6]
[2 3 4 5 6 7 8]]
Maximum value along the second axis:
[6 8]
Minimum value along the second axis:
[0 2]
```

In [ ]:
x= np.array([[0,1,2,3,4,5,6],[2,3,4,5,6,7,8]])
print(x.max(axis=1))
print(x.min(axis=1))

##### 29. Write a NumPy program to flatten the array and then find its median.
```
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
flat=x.flatten()
print(flat)
np.median(flat)

##### 30. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
```
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.percentile(x,80,axis=1)

###  Numpy Exercise

#### 1. Import the numpy package under the name np

In [ ]:
import numpy as np

#### 2. Create a numpy array of size 15 initialsed to zero.

In [ ]:
zeros=np.zeros(15)
zeros

#### 3. Create a numpy array of size 10 initiased to -1 but the fifth value which is 1

In [ ]:
numpy_array=np.full(10,-1)
print(numpy_array)

numpy_array[4]=1
print(numpy_array)

#### 4. Create a array with values ranging from 10 to 49 which are multiple of 3

In [ ]:
arr=np.arange(12,50,3)
arr

#### 5. Create and array with values ranging from 1 to 10 and Reverse the array (first element becomes last)

In [ ]:
np_arr=np.arange(1,11)
np_arr[::-1]

#### 6. Create a 10x10 array with random values with seed value 7 and find the minimum and maximum values for each row.

In [ ]:
np.random.seed(7)
x = np.random.random((10,10))
min_per_row=x.min(axis=1)
max_per_row=x.max(axis=1)

#### 7. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
```

a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
b=[[1,2],[3,4],[5,6]]

```

In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=np.array([[1,2],[3,4],[5,6]])
np.matmul(a,b)

#### 8. Given a 1D array, negate all elements which are between 3 and 8..And reshape to 3x5 shape
```
a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
```

In [ ]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a[(3 < a) & (a < 8)] *= -1
print(a)
reshaped_a = a.reshape(3,5)
print(reshaped_a)

#### 9. Create a 5x5 matrix with row values ranging from 0 to 4. Pad this 2D array with zero all around the border
#### Expected Output :
```
[
[0,0,0,0,0,0,0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0 0 1 2 3 4 0],
[0,0,0,0,0,0,0]
]
```

In [ ]:
x = np.zeros((5,5))
y= np.arange(5)
original=x+y
print(original)

# Create zeros col and row to append.
zeros_row=np.zeros(7,dtype=int).reshape(1,7)
zeros_col=np.zeros(5,dtype=int).reshape(5,1)

# append using vstack and hstack
padded=np.hstack((zeros_col,original,zeros_col))
padded=np.vstack((zeros_row,padded,zeros_row))
print(padded)

# Numpy also provide pad function 
print("Alternate Solution")
alternate = np.pad(original, pad_width=1, mode='constant', constant_values=0)
print(alternate)

#### 10. Read the following from file and fill missing values with 0
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt("a.txt",dtype=int,filling_values=0.0)

#### 11.  Given a array arr. Write a NumPy program to test element-wise for NaN of a given array.
```
arr = np.array([1, 0, np.nan, np.inf])
```

In [ ]:
arr = np.array([1, 0, np.nan, np.inf])
print(np.isnan(arr))

#### 12. Write a NumPy program to convert an array to a float type.
```
Original array 
[1, 2, 3, 4] 
Array converted to a float type: 
[ 1. 2. 3. 4.] 
```

In [ ]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

#### 13.  Write a NumPy program to construct an array by repeating.
```
Original array 
[1, 2, 3, 4] 
Repeating 2 times 
[1 2 3 4 1 2 3 4]
Repeating 3 times 
[1 2 3 4 1 2 3 4 1 2 3 4]
```

In [ ]:
n=3
x = np.tile(a, n)
x

#### 14. How to tell if a given 2D array has null columns?

In [ ]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("Test whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

#### 15. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
```
a= [
[1,2,3]
]

b= [
[4],
[5],
[6],
]

Expected Output = [[5 6 7]
                   [6 7 8]
                   [7 8 9]]
```


In [ ]:
A = np.arange(1,4).reshape(3,1)
B = np.arange(4,7).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

##### 16. Solve the linear equation
##### 10x+4y = 3 
#####  -x+5y = 2 

In [ ]:
A = np.array([[10, 4], [-1, 5]])
b = np.array([3,2])
x = np.linalg.solve(A, b)
x

##### 17. Create a 4x4 matrix with random values and find inverse of it.

In [ ]:
x= np.random.random((4,4))
print(x)
print("Inverse")
y = np.linalg.inv(x) 
print(y)

##### 18.  Consider following array replace every 3 with 0
```
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])
```

In [ ]:
array = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

array[(array == 3)] =0
array

##### 19. Considering these numpy array of person names and corresponding arrays for their age and gender. Findout names Who’s at least 44 in age.?
```
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])
```

In [ ]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

name= names[(ages >= 44)]
print(name)

###### 20. Based on above array. Which males are over 42?.

In [ ]:
name= names[(ages > 42) & (genders == 'male')]
print(name)

###### 21. Based on above array. Who’s a not a male or who is younger than 45? 

In [ ]:
name= names[(ages < 45) & (genders != 'male')]
name

##### 22. Given the following pairs of array-shapes, determine what the resulting broadcasted shapes will be.
##### Indicate if a pair is broadcast-incompatible.
```
1.    7 x 2 with 7
2.    4 with 3 x 4
3.    1 x 3 x 1 with 8 x 1 x 1
4.    9 x 2 x 5 with 2 x 5
5.    3 with 3 x 3 x 2 
```

```
Answer:
1. broadcast-incompatible
2. (3 x 4)
3. (8 x 3 x 1)
4. (9 x 2 x 5)
5. broadcast-incompatible
```

##### 23. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

##### Expected Output:
#### Original Array:
```
['python' 'PHP' 'java' 'C++']

Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

```

In [ ]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

##### 24. Write a NumPy program to split the element of a given array with spaces
```
Original Array:
 ['apple mangoes peach grapes']
Output
[list(['apple', 'mangoes', 'peach', 'grapes'])]
```

In [ ]:
x= np.array(['apple mangoes peach grapes'])
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

##### 25. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array
```
Original array:
[[10 40]
[30 20]]
Sort the array along the first axis:
[[10 20]
[30 40]]
Sort the array along the last axis:
[[10 40]
[20 30]]
Sort the flattened array:
[10 20 30 40] 
```

In [ ]:
x= np.array([[10,40],[30,20]])
print(x)
y=np.sort(x,axis=0)
print(y)
z=np.sort(x,axis=1)
print(z)
k=np.sort(x.flatten())
print(k)

##### 26. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
``` 
a= [1,3,5,6,7,8,9]
b= [10,11,23,45,67,12,13]
```

In [ ]:
a= np.array([1,3,5,6,7,8,9])
b= np.array([10,11,23,45,67,12,13])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

##### 27. Write a NumPy program to get the powers of 3 of an array values element-wise
```
a= [0 1 2 3 4 5 6]   
```

In [ ]:
a= np.array([0,1,2,3,4,5,6])
print(a**3)

###### 28. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
```
[[0 1 2 3 4 5 6]
[2 3 4 5 6 7 8]]
Maximum value along the second axis:
[6 8]
Minimum value along the second axis:
[0 2]
```

In [ ]:
x= np.array([[0,1,2,3,4,5,6],[2,3,4,5,6,7,8]])
print(x.max(axis=1))
print(x.min(axis=1))

##### 29. Write a NumPy program to flatten the array and then find its median.
```
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
flat=x.flatten()
print(flat)
np.median(flat)

##### 30. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
```
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
```

In [ ]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.percentile(x,80,axis=1)