## Creating 1-D array

In [1]:
import numpy as np
ar=np.array([1,4,6,3,7])
ar

array([1, 4, 6, 3, 7])

In [7]:
ar=np.array([1,4,6,3,7])
ar[2]

6

In [4]:
ar1=np.array((2,3,4,5))
ar1

array([2, 3, 4, 5])

## Creating 2-D array

In [5]:
arr=np.array([[1,2,4], [5,6,8]])
arr

array([[1, 2, 4],
       [5, 6, 8]])

In [8]:
arr=np.array([[1,2,4], [5,6,8]])
arr[0,1]

2

## Creating 3-D array

In [6]:
arr=np.array([[[1,2,3], [5,6,7]], [[1,2,3], [5,6,7]]])
arr

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

## Unary Operations

In [15]:
import numpy as np
arr=np.array([1,3,5,2,6])
np.cos(arr)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.41614684,  0.96017029])

In [16]:
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.79175947])

In [17]:
np.mean(arr)

3.4

In [18]:
np.median(arr)

3.0

In [19]:
np.std(arr)

1.8547236990991407

In [20]:
np.exp(arr)

array([  2.71828183,  20.08553692, 148.4131591 ,   7.3890561 ,
       403.42879349])

## Binary Operations

In [25]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])

arr1+arr2

array([ 5, 10,  7, 13,  4])

In [26]:
arr1-arr2

array([-1, -2,  5,  3,  0])

In [27]:
arr1*arr2

array([ 6, 24,  6, 40,  4])

## function

In [29]:
import numpy as np
arr=np.ones(2)
arr

array([1., 1.])

In [30]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [31]:
np.zeros(2)

array([0., 0.])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [34]:
arr=np.array([1.432, 3.087, 4.56])
np.around(arr)

array([1., 3., 5.])

In [35]:
np.around(arr,2)

array([1.43, 3.09, 4.56])

In [36]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
import numpy as np

print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4)
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [38]:

import numpy as np

print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [40]:
faces = np.random.randint(0,100,(10,3))
print(f'Set of 10 triplets\n\n{faces}')
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(f'\nUnique line segments composing all the triangles\n\n{G}')

Set of 10 triplets

[[10 63 72]
 [45 32 50]
 [40 61 13]
 [20 48 58]
 [77 68  4]
 [22 63 98]
 [58 20 34]
 [86 65 90]
 [13  7 21]
 [80 43  1]]

Unique line segments composing all the triangles

[( 1, 43) ( 1, 80) ( 4, 68) ( 4, 77) ( 7, 13) ( 7, 21) (10, 63) (10, 72)
 (13, 21) (13, 40) (13, 61) (20, 34) (20, 48) (20, 58) (22, 63) (22, 98)
 (32, 45) (32, 50) (34, 58) (40, 61) (43, 80) (45, 50) (48, 58) (63, 72)
 (63, 98) (65, 86) (65, 90) (68, 77) (86, 90)]


## Unary Operations

In [1]:
import numpy as np
arr=np.array([1,3,5,2,6])
np.cos(arr)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.41614684,  0.96017029])

In [2]:
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.79175947])

In [3]:
np.mean(arr)

3.4

In [4]:
np.median(arr)

3.0

In [5]:
np.std(arr)

1.8547236990991407

In [6]:
np.exp(arr)

array([  2.71828183,  20.08553692, 148.4131591 ,   7.3890561 ,
       403.42879349])

## Binary Operations

In [7]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])
arr1+arr2

array([ 5, 10,  7, 13,  4])

In [8]:
arr1-arr2

array([-1, -2,  5,  3,  0])

In [9]:
arr1*arr2

array([ 6, 24,  6, 40,  4])

In [2]:
import numpy as np
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])